"""add knowledge base tables

Revision ID: ac2e6ac71fab
Revises: d65a84d0b26a
Create Date: 2026-08-02 12:51:34.137077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2e6ac71fab'
down_revision: Union[str, None] = 'd65a84d0b26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_categories',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_categories_organization_id'), 'knowledge_base_categories', ['organization_id'], unique=False)
    op.create_table('knowledge_base_articles',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_base_categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_articles_category_id'), 'knowledge_base_articles', ['category_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_organization_id'), 'knowledge_base_articles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_articles_status'), 'knowledge_base_articles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_articles_status'), table_name='knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_articles_organization_id'), table_name='knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_articles_category_id'), table_name='knowledge_base_articles')
    op.drop_table('knowledge_base_articles')
    op.drop_index(op.f('ix_knowledge_base_categories_organization_id'), table_name='knowledge_base_categories')
    op.drop_table('knowledge_base_categories')
    # ### end Alembic commands ###
